info:
  component: Application Server ${spring.application.name}
# 加入服务发现
server:
  port: 8010
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/,http://127.0.0.1:8762/eureka/
  instance:
    prefer-ip-address: true
# 应用管理
management:
  health:
    refresh:
      enabled: true
  security:
    enabled: false
# 用户配置信息 配置调用服务接口
invokeService: spring-cloud-application-a
